# Generated by Django 4.2 on 2025-03-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_name', models.CharField(max_length=100)),
                ('hw_price', models.IntegerField()),
                ('write_off_length', models.IntegerField()),
                ('hw_production_date', models.DateTimeField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacement.brand')),
            ],
        ),
    ]
