# Generated by Django 4.2 on 2025-03-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replacement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='hw_production_date',
        ),
    ]
